"""Complete-v1 source-file-order workbook migration pass.

The legacy HubBuilder still knows how to derive many business formulas, but it
historically staged them on fixed FORM rows. This module treats those rows only
as staging evidence, then rewrites the final visible complete-v1 output by
source file order.
"""

from __future__ import annotations

from copy import copy
from dataclasses import dataclass
from pathlib import Path
import re
from typing import Iterable

from openpyxl import load_workbook
from openpyxl.formula.translate import Translator
from openpyxl.styles import PatternFill
from openpyxl.utils import get_column_letter

from src.engine.column_s_normalizer import worksheet_row_has_cost
from src.engine.source_order_output import CANONICAL_SOURCE_FILE_ORDER
from src.utils import excel_helpers as helpers

ACCOUNT_COL = 2
LOOKUP_NAME_COL = 3
LOOKUP_GROUP_COL = 4
ITEM_ID_COL = 5
MONTH_START_COL = 6
MONTH_END_COL = 17
TOTAL_COL = 18
DESCRIPTION_COL = 19
NOTE_COL = 20
BUSINESS_COLS = (ACCOUNT_COL, ITEM_ID_COL, *range(MONTH_START_COL, MONTH_END_COL + 1), DESCRIPTION_COL, NOTE_COL)
MONTH_COLS = tuple(range(MONTH_START_COL, MONTH_END_COL + 1))
MANAGED_CLEAR_COLS = tuple(range(2, 21))  # B:T, values/formulas only; styles are preserved.
COPY_COLS = tuple(range(1, 21))
LAYOUT_WHITE_COLUMNS = tuple(range(1, 5))
SOURCE_ORDER_MARKER = "source-order-complete-v1"
SOURCE_NOTE_RE = re.compile(r"source_file=([^;]+);\s*original_row=(\d+)")
ACCOUNT_MASTER_SHEET = "\u52d8\u5b9a\u79d1\u76ee"
NO_FILL = PatternFill(fill_type=None)
MISSING_SEPARATE_COUNT_FILL = PatternFill(fill_type="solid", fgColor="FFC7CE")
GENERATED_FILE_ORDER_POLICIES = (
    "ROUND_USD_BY_B2",
    "COPY_VND_MONTHLY",
    "COPY_SUMMARY_VND_TOTAL_BY_PERIOD",
    "COPY_SOURCE_MONTH_SAMPLE",
    "UNKNOWN",
)


@dataclass(frozen=True)
class StagedWorkbookRow:
    source_file: str
    original_row: int
    source_row: int
    values: dict[int, object]
    styles: dict[int, object]
    number_formats: dict[int, str]
    source_order_managed: bool = True
    red_month_cols: frozenset[int] = frozenset()


SOURCE_ROW_GROUPS = (
    # Facility rows staged by the legacy builder. These match the six visible
    # facility cost rows requested by the source-order export.
    (0, (36, 37, 40, 41, 44, 45)),
    # Fixed assets: depreciation and interest.
    (1, (38, 42)),
    # System cost is already generated by the file-order writer before this pass.
    (2, (179,)),
    # GA/Admin rows generated from 総務課, including bus rows staged on the
    # legacy FORM rows and consumables generated by the Admin file-order writer.
    (3, (53, 54, 175, 176, 177)),
    # Birthday.
    (4, (59,)),
    # Allocation-master/new employee rows previously staged on fixed FORM rows.
    (5, (57, 58, 97, 98)),
    # NNN paperwork.
    (6, (137,)),
)

LEGACY_FIXED_PLACEMENT_ROWS = (38, 42, 58, 59, 97, 98, 137)


def _norm(value: object) -> str:
    return "" if value is None else str(value).strip()


def _business_row_present(ws, row: int) -> bool:
    return any(_norm(ws.cell(row, col).value) for col in BUSINESS_COLS)


def _row_has_visible_month_cost(ws, row: int) -> bool:
    return worksheet_row_has_cost(ws, row, MONTH_COLS)


def _copy_staged_row(
    ws,
    source_file: str,
    row: int,
    original_row: int | None = None,
    *,
    require_visible_month_cost: bool = True,
    source_order_managed: bool = True,
) -> StagedWorkbookRow | None:
    if require_visible_month_cost and not _row_has_visible_month_cost(ws, row):
        return None
    if not require_visible_month_cost and not _business_row_present(ws, row):
        return None
    values: dict[int, object] = {}
    styles: dict[int, object] = {}
    number_formats: dict[int, str] = {}
    for col in COPY_COLS:
        cell = ws.cell(row, col)
        values[col] = cell.value
        if cell.has_style:
            styles[col] = copy(cell._style)
        number_formats[col] = cell.number_format
    return StagedWorkbookRow(
        source_file,
        int(original_row or row),
        int(row),
        values,
        styles,
        number_formats,
        source_order_managed=source_order_managed,
    )


def _clear_business_row(ws, row: int) -> None:
    for col in MANAGED_CLEAR_COLS:
        ws.cell(row, col).value = None


def _clear_rows(ws, rows: Iterable[int]) -> None:
    for row in rows:
        _clear_business_row(ws, row)


def _translated_formula(value: object, *, original_row: int, target_row: int, col: int) -> object:
    if not (isinstance(value, str) and value.startswith("=")) or original_row == target_row:
        return value
    coordinate = f"{get_column_letter(col)}{original_row}"
    target = f"{get_column_letter(col)}{target_row}"
    try:
        return Translator(value, origin=coordinate).translate_formula(target)
    except Exception:
        return value


def _lookup_name_formula(row: int) -> str:
    return (
        f'=IFERROR(IF(VLOOKUP($B{row},{ACCOUNT_MASTER_SHEET}!$A:$H,'
        f'HLOOKUP($E$5,{ACCOUNT_MASTER_SHEET}!$F$1:$H$2,2,0),0)="","",'
        f'VLOOKUP($B{row},{ACCOUNT_MASTER_SHEET}!$A:$E,2,0)),"")'
    )


def _lookup_group_formula(row: int) -> str:
    return f'=IF(C{row}="","",VLOOKUP($B{row},{ACCOUNT_MASTER_SHEET}!$A:$E,4,0))'


def _ensure_lookup_formulas(ws, row: int) -> None:
    if not _norm(ws.cell(row, ACCOUNT_COL).value) or not _row_has_visible_month_cost(ws, row):
        return
    if not _norm(ws.cell(row, LOOKUP_NAME_COL).value):
        ws.cell(row, LOOKUP_NAME_COL).value = _lookup_name_formula(row)
    if not _norm(ws.cell(row, LOOKUP_GROUP_COL).value):
        ws.cell(row, LOOKUP_GROUP_COL).value = _lookup_group_formula(row)


def _write_staged_row(ws, target_row: int, staged: StagedWorkbookRow) -> None:
    for col, value in staged.values.items():
        cell = ws.cell(target_row, col)
        cell.value = _translated_formula(
            value,
            original_row=staged.source_row,
            target_row=target_row,
            col=col,
        )
        if col in staged.styles:
            cell._style = copy(staged.styles[col])
        number_format = staged.number_formats.get(col)
        if number_format:
            cell.number_format = number_format

    if staged.source_order_managed:
        note = _source_order_note_base(ws.cell(target_row, NOTE_COL).value)
        source_note = f"source_file={staged.source_file}; original_row={staged.original_row}; {SOURCE_ORDER_MARKER}"
        ws.cell(target_row, NOTE_COL).value = f"{note} | {source_note}" if note else source_note
    for col in staged.red_month_cols:
        ws.cell(target_row, col).fill = copy(MISSING_SEPARATE_COUNT_FILL)
    _ensure_lookup_formulas(ws, target_row)
    ws.cell(target_row, TOTAL_COL).value = f"=SUM(F{target_row}:Q{target_row})"


def _normalize_final_output_layout(ws, start_row: int) -> dict[str, int]:
    cleared_fills = 0
    cleared_item_ids = 0
    for row in range(max(1, int(start_row)), int(ws.max_row or 0) + 1):
        for col in LAYOUT_WHITE_COLUMNS:
            cell = ws.cell(row, col)
            if cell.fill and cell.fill.fill_type:
                cleared_fills += 1
            cell.fill = copy(NO_FILL)
        item_cell = ws.cell(row, ITEM_ID_COL)
        if _norm(item_cell.value):
            item_cell.value = None
            cleared_item_ids += 1
    return {
        "layout_fills_cleared": cleared_fills,
        "item_ids_cleared": cleared_item_ids,
    }


def _source_rows_to_clear(ws) -> set[int]:
    rows_to_clear: set[int] = set()
    for _, rows in SOURCE_ROW_GROUPS:
        for row in rows:
            if _parse_source_order_note(ws.cell(row, NOTE_COL).value) is not None:
                continue
            if _business_row_present(ws, row):
                rows_to_clear.add(row)
    return rows_to_clear


def _collect_staged_rows(ws) -> list[StagedWorkbookRow]:
    staged: list[StagedWorkbookRow] = []
    for source_index, rows in SOURCE_ROW_GROUPS:
        source_file = CANONICAL_SOURCE_FILE_ORDER[source_index]
        for row in rows:
            if _has_generated_file_order_policy(ws.cell(row, NOTE_COL).value):
                continue
            item = _copy_staged_row(ws, source_file, row, require_visible_month_cost=False)
            if item is not None:
                staged.append(item)
    return staged


def _parse_source_order_note(note: object) -> tuple[str, int] | None:
    match = SOURCE_NOTE_RE.search(_norm(note))
    if not match:
        return None
    return match.group(1).strip(), int(match.group(2))


def _source_order_note_base(note: object) -> str:
    parts = [
        part.strip()
        for part in _norm(note).split("|")
        if part.strip() and SOURCE_ORDER_MARKER not in part
    ]
    return " | ".join(parts)


def _collect_existing_source_order_rows(ws, start_row: int, clear_until_row: int) -> list[StagedWorkbookRow]:
    staged: list[StagedWorkbookRow] = []
    seen: set[tuple[str, int, str, str, tuple[str, ...]]] = set()
    for row in range(int(start_row), int(clear_until_row) + 1):
        if _has_generated_file_order_policy(ws.cell(row, NOTE_COL).value):
            continue
        parsed = _parse_source_order_note(ws.cell(row, NOTE_COL).value)
        if parsed is None:
            continue
        source_file, original_row = parsed
        item = _copy_staged_row(ws, source_file, row, original_row, require_visible_month_cost=False)
        if item is not None:
            key = (
                item.source_file,
                item.original_row,
                _norm(item.values.get(ACCOUNT_COL)),
                _norm(item.values.get(DESCRIPTION_COL)),
                tuple(_norm(item.values.get(col)) for col in MONTH_COLS),
            )
            if key in seen:
                continue
            seen.add(key)
            staged.append(item)
    return staged


def _has_generated_file_order_policy(note: object) -> bool:
    text = _norm(note)
    return any(policy in text for policy in GENERATED_FILE_ORDER_POLICIES)


def _collect_preserved_unmanaged_rows(
    ws,
    start_row: int,
    clear_until_row: int,
    *,
    source_rows_to_clear: set[int],
) -> list[StagedWorkbookRow]:
    preserved: list[StagedWorkbookRow] = []
    rows_to_skip = set(source_rows_to_clear)
    for row in range(int(start_row), int(clear_until_row) + 1):
        if row in rows_to_skip:
            continue
        if _parse_source_order_note(ws.cell(row, NOTE_COL).value) is not None:
            continue
        if _has_generated_file_order_policy(ws.cell(row, NOTE_COL).value):
            continue
        if (
            not _row_has_visible_month_cost(ws, row)
            and not _norm(ws.cell(row, DESCRIPTION_COL).value)
            and not _norm(ws.cell(row, NOTE_COL).value)
        ):
            continue
        description = _norm(ws.cell(row, DESCRIPTION_COL).value)
        if description.lower().startswith("alloc:"):
            continue
        item = _copy_staged_row(
            ws,
            "",
            row,
            row,
            require_visible_month_cost=False,
            source_order_managed=False,
        )
        if item is not None:
            preserved.append(item)
    return preserved


def _collect_dynamic_allocation_rows(
    dynamic_allocation_rows: Iterable[dict[str, object]] | None,
    fiscal_periods: Iterable[str] | None,
) -> list[StagedWorkbookRow]:
    if not dynamic_allocation_rows or not fiscal_periods:
        return []
    period_to_col = {str(period): MONTH_START_COL + index for index, period in enumerate(fiscal_periods)}
    source_file = CANONICAL_SOURCE_FILE_ORDER[5]
    staged: list[StagedWorkbookRow] = []
    for index, row in enumerate(dynamic_allocation_rows, start=1):
        values: dict[int, object] = {
            ACCOUNT_COL: row.get("account_code"),
            DESCRIPTION_COL: row.get("description"),
        }
        highlight_periods = {str(period) for period in (row.get("highlight_periods") or set())}
        red_month_cols: set[int] = set()
        terms_by_period = row.get("terms") or {}
        numeric_by_period = row.get("numeric_months") or row.get("months") or {}
        for period, col in period_to_col.items():
            terms = list((terms_by_period or {}).get(period, []))
            numeric_value = float((numeric_by_period or {}).get(period, 0.0) or 0.0)
            if terms and numeric_value:
                terms.append(str(int(numeric_value)) if numeric_value.is_integer() else str(numeric_value))
            if terms:
                values[col] = "=" + "+".join(str(term).lstrip("=") for term in terms)
            elif numeric_value:
                values[col] = numeric_value
            if period in highlight_periods:
                red_month_cols.add(col)
        if not _norm(values.get(DESCRIPTION_COL)) or not _norm(values.get(ACCOUNT_COL)):
            continue
        staged.append(
            StagedWorkbookRow(
                source_file=source_file,
                original_row=10000 + index,
                source_row=10000 + index,
                values=values,
                styles={},
                number_formats={},
                source_order_managed=True,
                red_month_cols=frozenset(red_month_cols),
            )
        )
    return staged


def apply_complete_v1_source_order_to_workbook(
    workbook_path: str | Path,
    *,
    start_row: int = 30,
    clear_until_row: int = 212,
    dynamic_allocation_rows: Iterable[dict[str, object]] | None = None,
    fiscal_periods: Iterable[str] | None = None,
) -> dict[str, int]:
    """Rewrite complete-v1 business rows into canonical source-file blocks."""
    workbook_file = Path(workbook_path)
    wb = load_workbook(workbook_file)
    try:
        try:
            ws = wb[helpers.find_hub_sheet_name(wb)]
        except ValueError:
            ws = wb.active
        source_rows_to_clear = _source_rows_to_clear(ws)
        staged = _collect_existing_source_order_rows(ws, start_row, clear_until_row)
        if not staged:
            staged = _collect_staged_rows(ws)
        staged.extend(_collect_dynamic_allocation_rows(dynamic_allocation_rows, fiscal_periods))
        preserved = _collect_preserved_unmanaged_rows(
            ws,
            start_row,
            clear_until_row,
            source_rows_to_clear=source_rows_to_clear,
        )

        _clear_rows(ws, range(start_row, clear_until_row + 1))
        _clear_rows(ws, source_rows_to_clear)

        current_row = int(start_row)
        source_blocks_written = 0
        rows_written = 0
        blank_rows_written = 0

        for source_file in CANONICAL_SOURCE_FILE_ORDER:
            group = [row for row in staged if row.source_file == source_file]
            if not group:
                continue
            if source_blocks_written:
                _clear_business_row(ws, current_row)
                blank_rows_written += 1
                current_row += 1
            for item in group:
                _write_staged_row(ws, current_row, item)
                rows_written += 1
                current_row += 1
            source_blocks_written += 1

        preserved_rows_written = 0
        if preserved:
            if rows_written:
                _clear_business_row(ws, current_row)
                blank_rows_written += 1
                current_row += 1
            for item in preserved:
                _write_staged_row(ws, current_row, item)
                preserved_rows_written += 1
                current_row += 1

        layout_stats = _normalize_final_output_layout(ws, start_row)
        wb.save(workbook_file)
        return {
            "source_blocks_written": source_blocks_written,
            "rows_written": rows_written,
            "preserved_rows_written": preserved_rows_written,
            "blank_rows_written": blank_rows_written,
            "start_row": start_row,
            "end_row": current_row - 1 if rows_written or preserved_rows_written else start_row - 1,
            **layout_stats,
        }
    finally:
        wb.close()
