"""Complete-v1 source-file-order workbook migration pass.

The legacy HubBuilder still knows how to derive many business formulas, but it
historically staged them on fixed FORM rows. This module treats those rows only
as staging evidence, then rewrites the final visible complete-v1 output by
source file order.
"""

from __future__ import annotations

from copy import copy
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from openpyxl import load_workbook

from src.engine.column_s_normalizer import normalize_output_description_column_s
from src.engine.source_order_output import CANONICAL_SOURCE_FILE_ORDER
from src.utils import excel_helpers as helpers

ACCOUNT_COL = 2
ITEM_ID_COL = 5
MONTH_START_COL = 6
MONTH_END_COL = 17
DESCRIPTION_COL = 19
NOTE_COL = 20
BUSINESS_COLS = (ACCOUNT_COL, ITEM_ID_COL, *range(MONTH_START_COL, MONTH_END_COL + 1), DESCRIPTION_COL, NOTE_COL)
COPY_COLS = tuple(range(1, 21))


@dataclass(frozen=True)
class StagedWorkbookRow:
    source_file: str
    original_row: int
    values: dict[int, object]
    styles: dict[int, object]
    number_formats: dict[int, str]


SOURCE_ROW_GROUPS = (
    # Facility rows staged by the legacy builder. These match the six visible
    # facility cost rows requested by the source-order export.
    (0, (36, 37, 40, 41, 44, 45)),
    # Fixed assets: depreciation and interest.
    (1, (38, 42)),
    # System cost is already generated by the file-order writer before this pass.
    (2, (179,)),
    # Admin consumables are generated by the Admin file-order writer before this pass.
    (3, (175, 176, 177)),
    # Birthday.
    (4, (59,)),
    # Allocation-master/new employee rows previously staged on fixed FORM rows.
    (5, (57, 58, 97, 98)),
    # NNN paperwork.
    (6, (137,)),
)

LEGACY_FIXED_PLACEMENT_ROWS = (38, 42, 58, 59, 97, 98, 137)


def _norm(value: object) -> str:
    return "" if value is None else str(value).strip()


def _business_row_present(ws, row: int) -> bool:
    return any(_norm(ws.cell(row, col).value) for col in BUSINESS_COLS)


def _copy_staged_row(ws, source_file: str, row: int) -> StagedWorkbookRow | None:
    if not _business_row_present(ws, row):
        return None
    values: dict[int, object] = {}
    styles: dict[int, object] = {}
    number_formats: dict[int, str] = {}
    for col in COPY_COLS:
        cell = ws.cell(row, col)
        values[col] = cell.value
        if cell.has_style:
            styles[col] = copy(cell._style)
        number_formats[col] = cell.number_format
    return StagedWorkbookRow(source_file, row, values, styles, number_formats)


def _clear_business_row(ws, row: int) -> None:
    for col in BUSINESS_COLS:
        ws.cell(row, col).value = None


def _clear_rows(ws, rows: Iterable[int]) -> None:
    for row in rows:
        _clear_business_row(ws, row)


def _write_staged_row(ws, target_row: int, staged: StagedWorkbookRow) -> None:
    for col, value in staged.values.items():
        cell = ws.cell(target_row, col)
        cell.value = value
        if col in staged.styles:
            cell._style = copy(staged.styles[col])
        number_format = staged.number_formats.get(col)
        if number_format:
            cell.number_format = number_format

    note = _norm(ws.cell(target_row, NOTE_COL).value)
    source_note = f"source_file={staged.source_file}; original_row={staged.original_row}; source-order-complete-v1"
    ws.cell(target_row, NOTE_COL).value = f"{note} | {source_note}" if note else source_note


def _collect_staged_rows(ws) -> list[StagedWorkbookRow]:
    staged: list[StagedWorkbookRow] = []
    for source_index, rows in SOURCE_ROW_GROUPS:
        source_file = CANONICAL_SOURCE_FILE_ORDER[source_index]
        for row in rows:
            item = _copy_staged_row(ws, source_file, row)
            if item is not None:
                staged.append(item)
    return staged


def apply_complete_v1_source_order_to_workbook(
    workbook_path: str | Path,
    *,
    start_row: int = 168,
    clear_until_row: int = 212,
) -> dict[str, int]:
    """Rewrite complete-v1 business rows into canonical source-file blocks."""
    workbook_file = Path(workbook_path)
    wb = load_workbook(workbook_file)
    try:
        try:
            ws = wb[helpers.find_hub_sheet_name(wb)]
        except ValueError:
            ws = wb.active
        staged = _collect_staged_rows(ws)

        _clear_rows(ws, range(start_row, clear_until_row + 1))
        _clear_rows(ws, LEGACY_FIXED_PLACEMENT_ROWS)

        current_row = int(start_row)
        source_blocks_written = 0
        rows_written = 0
        blank_rows_written = 0

        for source_file in CANONICAL_SOURCE_FILE_ORDER:
            group = [row for row in staged if row.source_file == source_file]
            if not group:
                continue
            if source_blocks_written:
                _clear_business_row(ws, current_row)
                blank_rows_written += 1
                current_row += 1
            for item in group:
                _write_staged_row(ws, current_row, item)
                rows_written += 1
                current_row += 1
            source_blocks_written += 1

        normalize_output_description_column_s(ws)
        wb.save(workbook_file)
        return {
            "source_blocks_written": source_blocks_written,
            "rows_written": rows_written,
            "blank_rows_written": blank_rows_written,
            "start_row": start_row,
            "end_row": current_row - 1 if rows_written else start_row - 1,
        }
    finally:
        wb.close()
